export const ROUTES = {
  landing: "/",
  login: "/login",
  register: "/register",
  verifyEmail: "/verify-email",
  welcome: "/welcome",
  intro: "/intro",
  connect: "/connect",
  import: "/import",
  dashboard: "/dashboard",
  analytics: "/analytics",
  leaderboard: "/leaderboard",
  contests: "/contests",
  achievements: "/achievements",
  profile: "/profile",
  settings: "/settings",
  aiCoach: "/ai-coach",
  notifications: "/notifications",
  friends: "/friends",
  goals: "/goals",
};
