const PDFDocument = require("pdfkit");
const sharp = require("sharp");

const exportRepository = require("../repositories/exportRepository");

const escHtml = (s) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const generateJsonReport = async (userId) => {
    const [user, stats, profiles, achievements, activities] = await Promise.all([
        exportRepository.findUserInfo(userId),
        exportRepository.findStats(userId),
        exportRepository.findProfiles(userId),
        exportRepository.findAchievements(userId),
        exportRepository.findActivities(userId),
    ]);

    return { user, stats, profiles, achievements, activities };
};

const generatePdfReport = async (userId) => {
    const report = await generateJsonReport(userId);

    const doc = new PDFDocument();
    const chunks = [];

    doc.on("data", chunk => chunks.push(chunk));

    return new Promise((resolve, reject) => {
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);

        try {
            doc.fontSize(22).text("DEVTRACK AI REPORT", { align: "center" });
            doc.moveDown();

            doc.fontSize(16).text(`Name: ${report.user.name}`);
            doc.text(`Email: ${report.user.email}`);
            doc.text(`Total Solved: ${report.stats?.total_solved ?? 0}`);
            doc.text(`Current Streak: ${report.stats?.streak ?? 0}`);
            doc.text(`GitHub Contributions: ${report.stats?.contributions ?? 0}`);
            doc.moveDown();

            doc.fontSize(18).text("Profiles");

            (report.profiles || []).forEach(profile => {
                doc.text(`${profile.platform}: ${profile.username}`);
            });

            doc.moveDown();
            doc.fontSize(18).text("Achievements");

            (report.achievements || []).forEach(achievement => {
                doc.text(achievement.title);
            });

            doc.moveDown();
            doc.fontSize(18).text("Recent Activities");

            (report.activities || []).forEach(activity => {
                const desc = activity.metadata?.description || activity.action || "";
                doc.text(desc || activity.description || "");
            });

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
};

const generatePngReport = async (userId) => {
    const report = await generateJsonReport(userId);

    const user = report.user;
    const stats = report.stats;

    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400">
  <rect width="600" height="400" fill="#0D1117" rx="16"/>
  <rect x="0" y="0" width="600" height="100" fill="#161B22" rx="16"/>
  <rect x="0" y="85" width="600" height="15" fill="#161B22"/>
  <text x="300" y="45" font-family="Arial,sans-serif" font-size="22" font-weight="bold" fill="#F8FAFC" text-anchor="middle">DEVTRACK AI</text>
  <text x="300" y="75" font-family="Arial,sans-serif" font-size="14" fill="#8B949E" text-anchor="middle">Developer Progress Report</text>
  <text x="30" y="150" font-family="Arial,sans-serif" font-size="16" font-weight="bold" fill="#F8FAFC">${escHtml(user?.name)}</text>
  <text x="30" y="175" font-family="Arial,sans-serif" font-size="12" fill="#8B949E">${escHtml(user?.email)}</text>
  <rect x="30" y="195" width="540" height="1" fill="#30363D"/>
  <text x="30" y="225" font-family="Arial,sans-serif" font-size="14" fill="#7C3AED" font-weight="bold">Stats</text>
  <text x="30" y="250" font-family="Arial,sans-serif" font-size="12" fill="#F8FAFC">Total Solved</text>
  <text x="250" y="250" font-family="Arial,sans-serif" font-size="12" fill="#22C55E" text-anchor="end">${stats?.total_solved ?? 0}</text>
  <text x="30" y="275" font-family="Arial,sans-serif" font-size="12" fill="#F8FAFC">Streak</text>
  <text x="250" y="275" font-family="Arial,sans-serif" font-size="12" fill="#22C55E" text-anchor="end">${stats?.streak ?? 0} days</text>
  <text x="30" y="300" font-family="Arial,sans-serif" font-size="12" fill="#F8FAFC">GitHub Contributions</text>
  <text x="250" y="300" font-family="Arial,sans-serif" font-size="12" fill="#22C55E" text-anchor="end">${stats?.contributions ?? 0}</text>
  ${report.profiles?.length > 0 ? `<text x="30" y="335" font-family="Arial,sans-serif" font-size="14" fill="#6366F1" font-weight="bold">Connected Platforms</text>
  ${report.profiles.slice(0, 3).map((p, i) => `<text x="30" y="${360 + i * 20}" font-family="Arial,sans-serif" font-size="12" fill="#F8FAFC">${escHtml(p.platform)}</text>
  <text x="250" y="${360 + i * 20}" font-family="Arial,sans-serif" font-size="12" fill="#8B949E" text-anchor="end">${escHtml(p.username)}</text>`).join("")}` : ""}
  <text x="300" y="390" font-family="Arial,sans-serif" font-size="10" fill="#30363D" text-anchor="middle">Generated by DevTrack AI</text>
</svg>`;

    return await sharp(Buffer.from(svg)).png().toBuffer();
};

module.exports = {
    generatePdfReport,
    generateJsonReport,
    generatePngReport,
};